permutation_choice_two (perm_choice_two_output, perm_choice_two_input);

input [56:1] perm_choice_two_input;
output wire [48:1] perm_choice_two_output;

assign perm_choice_two_output[1]= perm_choice_two_input[14];
assign perm_choice_two_output[2]= perm_choice_two_input[17];
assign perm_choice_two_output[3]= perm_choice_two_input[11];
assign perm_choice_two_output[4]= perm_choice_two_input[24];
assign perm_choice_two_output[5]= perm_choice_two_input[1];
assign perm_choice_two_output[6]= perm_choice_two_input[5];
assign perm_choice_two_output[7]= perm_choice_two_input[3];
assign perm_choice_two_output[8]= perm_choice_two_input[28];
assign perm_choice_two_output[9]= perm_choice_two_input[15];
assign perm_choice_two_output[10]= perm_choice_two_input[6];
assign perm_choice_two_output[11]= perm_choice_two_input[21];
assign perm_choice_two_output[12]= perm_choice_two_input[10];
assign perm_choice_two_output[13]= perm_choice_two_input[23];
assign perm_choice_two_output[14]= perm_choice_two_input[19];
assign perm_choice_two_output[15]= perm_choice_two_input[12];
assign perm_choice_two_output[16]= perm_choice_two_input[4];
assign perm_choice_two_output[17]= perm_choice_two_input[26];
assign perm_choice_two_output[18]= perm_choice_two_input[8];
assign perm_choice_two_output[19]= perm_choice_two_input[16];
assign perm_choice_two_output[20]= perm_choice_two_input[7];
assign perm_choice_two_output[21]= perm_choice_two_input[27];
assign perm_choice_two_output[22]= perm_choice_two_input[20];
assign perm_choice_two_output[23]= perm_choice_two_input[13];
assign perm_choice_two_output[24]= perm_choice_two_input[2];
assign perm_choice_two_output[25]= perm_choice_two_input[41];
assign perm_choice_two_output[26]= perm_choice_two_input[52];
assign perm_choice_two_output[27]= perm_choice_two_input[31];
assign perm_choice_two_output[28]= perm_choice_two_input[37];
assign perm_choice_two_output[29]= perm_choice_two_input[47];
assign perm_choice_two_output[30]= perm_choice_two_input[55];
assign perm_choice_two_output[31]= perm_choice_two_input[30];
assign perm_choice_two_output[32]= perm_choice_two_input[40];
assign perm_choice_two_output[33]= perm_choice_two_input[51];
assign perm_choice_two_output[34]= perm_choice_two_input[45];
assign perm_choice_two_output[35]= perm_choice_two_input[33];
assign perm_choice_two_output[36]= perm_choice_two_input[48];
assign perm_choice_two_output[37]= perm_choice_two_input[44];
assign perm_choice_two_output[38]= perm_choice_two_input[49];
assign perm_choice_two_output[39]= perm_choice_two_input[39];
assign perm_choice_two_output[40]= perm_choice_two_input[56];
assign perm_choice_two_output[41]= perm_choice_two_input[34];
assign perm_choice_two_output[42]= perm_choice_two_input[53];
assign perm_choice_two_output[43]= perm_choice_two_input[46];
assign perm_choice_two_output[44]= perm_choice_two_input[42];
assign perm_choice_two_output[45]= perm_choice_two_input[50];
assign perm_choice_two_output[46]= perm_choice_two_input[36];
assign perm_choice_two_output[47]= perm_choice_two_input[29];
assign perm_choice_two_output[48]= perm_choice_two_input[32];

endmodule